Servo
viamrobotics/viam-java-sdk pull request #60
Opened 2024-08-28 16:15 UTC by gloriacai01

Add servo component wrappers in java sdk + associated tests

2024-08-30 16:55 UTC, njooma requested changes
Almost! Seems like you forgot `doCommand` in a few places. But overall this is great!

2024-08-30 16:55 UTC, njooma commented on core/sdk/src/main/java/com/viam/sdk/core/component/servo/ServoRPCService.java
> +    }
This file is missing `doCommand`

2024-08-30 16:55 UTC, njooma commented on core/sdk/src/test/kotlin/com/viam/sdk/core/component/servo/ServoRPCClientTest.kt
> +
Missing the test for `doCommand`

2024-09-09 16:09 UTC, lia-viam approved these changes

2024-09-09 16:10 UTC, lia-viam commented
I think this needs a rebase but other than that you're probably good to merge!

2024-09-09 17:10 UTC, purplenicole730 approved these changes
For better recording purposes, please include the ticket number in the title of this PR. (It also helps with integrating with Jira)

ex: RSDK-XXXX: add servo wrappers

2024-09-11 18:40 UTC, merged